version: '2'

services:
  redis:
    image: redis:2.8
    ports:
      - 6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672
      - 5672

  zk:
    image: jplock/zookeeper:3.5.2-alpha
    ports:
      - 2181

  fan:
    build: .
    command: bash -c "sleep 15 && pytest"
#    command: sleep infinity
#    volumes:
#      - .:/code
    depends_on:
      - redis
      - rabbitmq
      - zk
